var namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory =
[
    [ "OOP", "namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory_1_1_o_o_p.html", "namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory_1_1_o_o_p" ],
    [ "OOPTemplate", "namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory_1_1_o_o_p_template.html", "namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory_1_1_o_o_p_template" ],
    [ "Procedural", "namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory_1_1_procedural.html", "namespace_a_d_s_library_1_1_data_structures_1_1_array_based_structures_1_1_fixed_memory_1_1_procedural" ]
];