var namespace_a_d_s_library_1_1_data_structures_1_1_linked_structures_1_1_o_o_p_template =
[
    [ "Queue", "class_a_d_s_library_1_1_data_structures_1_1_linked_structures_1_1_o_o_p_template_1_1_queue.html", "class_a_d_s_library_1_1_data_structures_1_1_linked_structures_1_1_o_o_p_template_1_1_queue" ],
    [ "Stack", "class_a_d_s_library_1_1_data_structures_1_1_linked_structures_1_1_o_o_p_template_1_1_stack.html", "class_a_d_s_library_1_1_data_structures_1_1_linked_structures_1_1_o_o_p_template_1_1_stack" ]
];